apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llama-inference-kong
  # namespace: kserve-test
  annotations:
    konghq.com/plugins: key-auth
spec:
  ingressClassName: kong
  rules:
    - host: llama.demo.cluster
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llama-3-2-1b-instruct-predictor-00001
                port:
                  number: 80
