apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-internal.default.svc.cluster.local:8200"    # adapte la FQDN et le port selon le service Vault déployé
      path: "kv/"
      version: "v1"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets

# my-svc.my-namespace.svc.cluster-local

