apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-apikeys-configmap
  namespace: ingress-nginx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ingress-nginx-controller
    template:
      type: Opaque
      data:
        http-snippet: |
          map $http_apikey $api_key_owner {
            "key_A" "{{ .key_A }}"
            "key_B" "{{ .key_B }}"
            default "";
          }
        allow-snippet-annotations: "true"
        annotations-risk-level: Critical
  data:
    - secretKey: key_A
      remoteRef:
        key: nginx-apikeys
        property: key_A
    - secretKey: key_B
      remoteRef:
        key: nginx-apikeys
        property: key_B
