# This vLLM Dockerfile is used to construct image that can build and run vLLM on x86 CPU platform.
# Build this image at the root of this git repo: https://github.com/vllm-project/vllm/tree/main
FROM ubuntu:22.04

RUN apt-get update  -y \
    && apt-get install -y gcc-12 g++-12 libnuma-dev python3-dev python3-pip git \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12

COPY ./ /workspace/vllm

WORKDIR /workspace/vllm

RUN pip install --upgrade pip \
    && pip install "cmake>=3.26.1" wheel packaging ninja "setuptools-scm>=8" numpy \
    && pip install -v -r requirements/cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu

RUN VLLM_TARGET_DEVICE=cpu python3 setup.py install

CMD ["/bin/bash"]