apiVersion: v1
kind: Service
metadata:
  name: streamlit-server
  namespace: kserve-test 
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: streamlit
  ports:
  - name: "8501"
    port: 8501
    targetPort: 8501